/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-adsb_alt_framer
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_ADSB_ALT_FRAMER_API_H
#define INCLUDED_ADSB_ALT_FRAMER_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_adsb_alt_framer_EXPORTS
#define ADSB_ALT_FRAMER_API __GR_ATTR_EXPORT
#else
#define ADSB_ALT_FRAMER_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_ADSB_ALT_FRAMER_API_H */
