/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(alt_framer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(604ecb44916e00bbddc4f180672a5ad0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/adsb_alt_framer/alt_framer.h>
// pydoc.h is automatically generated in the build directory
#include <alt_framer_pydoc.h>

void bind_alt_framer(py::module& m)
{

    using alt_framer    = gr::adsb_alt_framer::alt_framer;


    py::class_<alt_framer, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<alt_framer>>(m, "alt_framer", D(alt_framer))

        .def(py::init(&alt_framer::make),
           D(alt_framer,make)
        )
        



        ;




}








